"""Add user role

Revision ID: 43750b91dc20
Revises: c7d58cb9f610
Create Date: 2026-09-07 00:52:00.781189

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43750b91dc20"
down_revision: str | Sequence[str] | None = "c7d58cb9f610"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuario",
        sa.Column(
            "rol", sa.String(length=20), server_default="usuario", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "rol")
    # ### end Alembic commands ###
