"""Add descripcion to prueba

Revision ID: 6d380b11f95a
Revises: 946408d2c5c3
Create Date: 2026-09-06 18:51:44.846508

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d380b11f95a"
down_revision: str | Sequence[str] | None = "946408d2c5c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prueba", sa.Column("descripcion", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prueba", "descripcion")
    # ### end Alembic commands ###
