"""Add categoria relation to prueba

Revision ID: faff9cb6b371
Revises: 6d380b11f95a
Create Date: 2026-09-06 20:18:58.394397

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faff9cb6b371"
down_revision: str | Sequence[str] | None = "6d380b11f95a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("prueba", sa.Column("categoria_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "prueba", "categoria", ["categoria_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prueba", type_="foreignkey")
    op.drop_column("prueba", "categoria_id")
    op.drop_table("categoria")
    # ### end Alembic commands ###
